---
packages:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - kubeadm
  - kubelet
  - kubectl

ports:
  - 6443/tcp
  - 2379-2380/tcp
  - 10250/tcp
  - 10251/tcp
  - 10252/tcp